apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: registry.3incloud.com/service-b:1.0-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
      imagePullSecrets:
        - name: gyhlw-registry
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: service-b